import fs from 'fs';
import path from 'path';

// Curated 60+ distinct verified construction & hardware images
const productData = [
  // 1. Structural & Masonry (8 items)
  {
    id: 'p_cement_1',
    name: 'UltraTech Super Cement 53 Grade',
    brand: 'UltraTech',
    category: 'Structural & Masonry',
    unit: '50 kg Bag',
    imageUrl: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=800&q=80',
    description: 'High performance Ordinary Portland Cement (OPC 53) engineered for high early strength, ideal for RCC columns, beams, slabs and foundations.',
    sku: 'CEM-ULT-53G',
    specifications: { 'Grade': 'OPC 53 Grade', 'Packaging': 'HDPE Laminated Bag', 'Weight': '50 kg', 'Setting Time': '30 mins initial / 600 mins final', 'Standard': 'IS 269:2015' },
    minOrderQty: 10,
    bulkDiscountTiers: [{ minQty: 50, discountPct: 4 }, { minQty: 100, discountPct: 8 }],
    rating: 4.8,
    reviewCount: 342,
    basePrice: 385,
    mrp: 430
  },
  {
    id: 'p_cement_2',
    name: 'Ambuja Kawach Water-Shield Cement',
    brand: 'Ambuja',
    category: 'Structural & Masonry',
    unit: '50 kg Bag',
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    description: 'Specially formulated water-repellent cement with active silanes that prevents water seepage and efflorescence in basements and roofs.',
    sku: 'CEM-AMB-KWCH',
    specifications: { 'Type': 'Waterproof PPC', 'Packaging': 'Tamper-proof Poly Bag', 'Weight': '50 kg', 'Water Permeability': '85% Reduced Seepage' },
    minOrderQty: 10,
    bulkDiscountTiers: [{ minQty: 40, discountPct: 5 }, { minQty: 100, discountPct: 9 }],
    rating: 4.7,
    reviewCount: 198,
    basePrice: 410,
    mrp: 460
  },
  {
    id: 'p_steel_1',
    name: 'Tata Tiscon 550D TMT Steel Rebars (12mm)',
    brand: 'Tata Tiscon',
    category: 'Structural & Masonry',
    unit: 'Piece (12m)',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    description: 'Super-ductile Fe 550D grade thermo-mechanically treated steel rebars with superior earthquake resistance and rib pattern for concrete grip.',
    sku: 'STL-TATA-12MM',
    specifications: { 'Diameter': '12 mm', 'Standard Length': '12 meters (40 ft)', 'Grade': 'Fe 550D', 'Elongation': '16% minimum', 'Certification': 'IS 1786:2008' },
    minOrderQty: 20,
    bulkDiscountTiers: [{ minQty: 50, discountPct: 3 }, { minQty: 100, discountPct: 6 }],
    rating: 4.9,
    reviewCount: 512,
    basePrice: 780,
    mrp: 850
  },
  {
    id: 'p_steel_2',
    name: 'JSW Neosteel Fe 550D TMT Rebar (16mm)',
    brand: 'JSW Steel',
    category: 'Structural & Masonry',
    unit: 'Piece (12m)',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    description: 'High-strength alloyed TMT rebar for heavy foundation piling, bridges, and multi-storey commercial columns.',
    sku: 'STL-JSW-16MM',
    specifications: { 'Diameter': '16 mm', 'Grade': 'Fe 550D', 'Length': '12m', 'Yield Strength': '550 N/mm²' },
    minOrderQty: 15,
    bulkDiscountTiers: [{ minQty: 50, discountPct: 4 }],
    rating: 4.8,
    reviewCount: 178,
    basePrice: 1390,
    mrp: 1520
  },
  {
    id: 'p_bricks_1',
    name: 'Kiln-Burned Red Clay Construction Bricks',
    brand: 'Local Kiln Verified',
    category: 'Structural & Masonry',
    unit: '1,000 Pcs Load',
    imageUrl: 'https://images.unsplash.com/photo-1584463699026-6799f2420993?auto=format&fit=crop&w=800&q=80',
    description: 'First-class wire-cut kiln baked clay bricks with sharp square edges, uniform burnt red color, and high compressive load rating.',
    sku: 'BRK-RED-1000',
    specifications: { 'Dimensions': '9 x 4.25 x 2.75 inches', 'Compressive Strength': '7.5 N/mm²', 'Water Absorption': '< 15%' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 3, discountPct: 5 }, { minQty: 5, discountPct: 10 }],
    rating: 4.6,
    reviewCount: 120,
    basePrice: 8500,
    mrp: 9500
  },
  {
    id: 'p_sand_1',
    name: 'Washed River Sand (Coarse Grade)',
    brand: 'Riverbed Premium',
    category: 'Structural & Masonry',
    unit: 'Brass (100 cu ft)',
    imageUrl: 'https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?auto=format&fit=crop&w=800&q=80',
    description: 'Triple-washed river sand free from organic matter and silt, optimal for plastering, slab casting, and structural RCC mortar mixes.',
    sku: 'SND-RIV-1BRS',
    specifications: { 'Zone': 'Zone II Coarse Sand', 'Silt Content': '< 3%', 'Moisture': 'Air-dried' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 2, discountPct: 4 }, { minQty: 4, discountPct: 8 }],
    rating: 4.7,
    reviewCount: 94,
    basePrice: 6200,
    mrp: 7000
  },
  {
    id: 'p_blocks_1',
    name: 'AAC Lightweight Autoclaved Aerated Blocks',
    brand: 'Aerocon',
    category: 'Structural & Masonry',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80',
    description: 'Thermal insulating lightweight masonry blocks providing 3x faster construction and 50% dead-weight structural load reduction.',
    sku: 'BLK-AAC-6IN',
    specifications: { 'Dimensions': '600 x 200 x 150 mm', 'Fire Rating': '4 Hours', 'Density': '550-650 kg/m³' },
    minOrderQty: 50,
    bulkDiscountTiers: [{ minQty: 200, discountPct: 6 }, { minQty: 500, discountPct: 12 }],
    rating: 4.6,
    reviewCount: 84,
    basePrice: 65,
    mrp: 75
  },
  {
    id: 'p_aggregate_1',
    name: 'Crushed Blue Granite Aggregate (20mm Jelly)',
    brand: 'StoneQuarry Core',
    category: 'Structural & Masonry',
    unit: 'Brass (100 cu ft)',
    imageUrl: 'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=800&q=80',
    description: 'Angular graded 20mm hard granite ballast stone aggregate for high strength concrete slab mixing.',
    sku: 'AGG-BLU-20MM',
    specifications: { 'Size': '20 mm graded', 'Crushing Value': '< 25%', 'Unit Weight': '1550 kg/m³' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 3, discountPct: 5 }],
    rating: 4.8,
    reviewCount: 76,
    basePrice: 4800,
    mrp: 5400
  },

  // 2. Electrical & Lighting (8 items)
  {
    id: 'p_wire_1',
    name: 'Havells Life Line Plus HRFR Copper Wire 2.5 sq mm',
    brand: 'Havells',
    category: 'Electrical & Lighting',
    unit: '90m Coil',
    imageUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?auto=format&fit=crop&w=800&q=80',
    description: 'Heat Resistant Flame Retardant (HRFR) electrolytic grade 99.97% pure copper multi-strand domestic and commercial house wire.',
    sku: 'WIR-HAV-2.5MM',
    specifications: { 'Conductor': '100% Electrolytic Bare Copper', 'Voltage Grade': '1100V', 'Insulation': 'HRFR PVC 105°C', 'Coil Length': '90 meters' },
    minOrderQty: 2,
    bulkDiscountTiers: [{ minQty: 10, discountPct: 5 }, { minQty: 25, discountPct: 10 }],
    rating: 4.9,
    reviewCount: 420,
    basePrice: 2450,
    mrp: 2900
  },
  {
    id: 'p_wire_2',
    name: 'Polycab Green Shield 4.0 sq mm Heavy Load Cable',
    brand: 'Polycab',
    category: 'Electrical & Lighting',
    unit: '90m Coil',
    imageUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?auto=format&fit=crop&w=800&q=80',
    description: 'Heavy duty copper wire suitable for air conditioner lines, water geysers, and industrial power distribution.',
    sku: 'WIR-POL-4.0MM',
    specifications: { 'Conductor': 'Class 5 Flexible Copper', 'Current Capacity': '29 Amps', 'Standard': 'IS 694' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 5, discountPct: 6 }],
    rating: 4.8,
    reviewCount: 154,
    basePrice: 3890,
    mrp: 4500
  },
  {
    id: 'p_switch_1',
    name: 'Schneider Electric Opale 10A 1-Way Modular Switch',
    brand: 'Schneider',
    category: 'Electrical & Lighting',
    unit: 'Box of 20',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    description: 'Sleek satin white anti-spark modular switch with silver cadmium oxide contacts rated for 1,00,000+ flawless switching operations.',
    sku: 'SWT-SCH-10A-W',
    specifications: { 'Rating': '10A 240V AC', 'Material': 'Fire-retardant Polycarbonate', 'Finish': 'Glossy Arctic White', 'Pack Size': '20 Pieces' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 5, discountPct: 6 }, { minQty: 10, discountPct: 12 }],
    rating: 4.8,
    reviewCount: 164,
    basePrice: 780,
    mrp: 950
  },
  {
    id: 'p_mcb_1',
    name: 'Legrand RX3 32A C-Curve Double Pole MCB',
    brand: 'Legrand',
    category: 'Electrical & Lighting',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    description: 'Miniature Circuit Breaker with 10kA breaking capacity for complete short circuit & overload protection on air conditioner lines.',
    sku: 'MCB-LEG-32A-DP',
    specifications: { 'Current Rating': '32A', 'Poles': '2 Pole (DP)', 'Tripping Curve': 'Type C', 'Breaking Capacity': '10 kA' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 10, discountPct: 7 }],
    rating: 4.8,
    reviewCount: 92,
    basePrice: 620,
    mrp: 750
  },
  {
    id: 'p_light_1',
    name: 'Philips Ultima 50W Outdoor LED Floodlight',
    brand: 'Philips',
    category: 'Electrical & Lighting',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?auto=format&fit=crop&w=800&q=80',
    description: 'IP66 weatherproof die-cast aluminum construction site security floodlight delivering 5000 lumens crisp cool daylight illumination.',
    sku: 'LGT-PHI-50W-FLD',
    specifications: { 'Power': '50 Watts', 'Lumen Output': '5000 lm', 'Color Temp': '6500K Cool Day White', 'Weatherproof': 'IP66 Rated' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 4, discountPct: 8 }],
    rating: 4.7,
    reviewCount: 145,
    basePrice: 1450,
    mrp: 1850
  },
  {
    id: 'p_conduit_1',
    name: 'Precision Heavy Duty PVC Electrical Conduit 25mm',
    brand: 'Precision',
    category: 'Electrical & Lighting',
    unit: 'Bundle (10 Pcs x 3m)',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    description: 'Impact resistant fire retardant rigid PVC electrical conduits for concealed wall chiseling and false ceiling cable wiring.',
    sku: 'CND-PRC-25MM',
    specifications: { 'Diameter': '25 mm', 'Wall Thickness': 'Heavy Gauge', 'Length': '3m per pipe', 'Bundle': '10 Pipes (30m total)' },
    minOrderQty: 2,
    bulkDiscountTiers: [{ minQty: 5, discountPct: 5 }],
    rating: 4.6,
    reviewCount: 78,
    basePrice: 680,
    mrp: 800
  },
  {
    id: 'p_db_box_1',
    name: 'Schneider 8-Way SPN Distribution Board (IP43)',
    brand: 'Schneider',
    category: 'Electrical & Lighting',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    description: 'Sheet steel enclosed flush-mount consumer distribution board with insulated busbars and earth/neutral terminal links.',
    sku: 'DB-SCH-8WAY',
    specifications: { 'Ways': '8 Way SPN', 'Material': 'CRCA Sheet Steel with Powder Coating', 'Protection': 'IP43 Door Shield' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 4, discountPct: 6 }],
    rating: 4.7,
    reviewCount: 56,
    basePrice: 1250,
    mrp: 1490
  },
  {
    id: 'p_fan_1',
    name: 'Atomberg Renesa 1200mm BLDC Ceiling Fan',
    brand: 'Atomberg',
    category: 'Electrical & Lighting',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    description: 'Energy-efficient 28W brushless DC motor fan with smart LED remote control and inverter backup longevity.',
    sku: 'FAN-ATM-1200-W',
    specifications: { 'Sweep': '1200 mm (48 inch)', 'Power Consumption': '28 Watts BLDC', 'Air Delivery': '235 CMM', 'Warranty': '3 Years' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 4, discountPct: 5 }],
    rating: 4.8,
    reviewCount: 230,
    basePrice: 3699,
    mrp: 4450
  },

  // 3. Plumbing & Sanitary (8 items)
  {
    id: 'p_pipe_1',
    name: 'Astral CPVC PRO SDR 11 Hot & Cold Pipe 1"',
    brand: 'Astral',
    category: 'Plumbing & Sanitary',
    unit: 'Piece (3m)',
    imageUrl: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80',
    description: 'Lead-free NSF certified high-temperature chlorinated polyvinyl chloride pressure plumbing pipe tested up to 93°C hot water.',
    sku: 'PIP-AST-1IN-SDR11',
    specifications: { 'Size': '1 inch (25mm NB)', 'Pressure Class': 'SDR 11 (28.1 kg/cm²)', 'Length': '3 meters (10 ft)', 'Standard': 'ASTM D2846' },
    minOrderQty: 5,
    bulkDiscountTiers: [{ minQty: 20, discountPct: 5 }, { minQty: 50, discountPct: 10 }],
    rating: 4.9,
    reviewCount: 284,
    basePrice: 420,
    mrp: 490
  },
  {
    id: 'p_tank_1',
    name: 'Sintex Pure 4-Layer 1000L Overhead Water Tank',
    brand: 'Sintex',
    category: 'Plumbing & Sanitary',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    description: '100% virgin food grade polyethylene water storage tank with anti-bacterial inner layer and UV sun protection barrier.',
    sku: 'TNK-SIN-1000L-4L',
    specifications: { 'Capacity': '1,000 Litres', 'Layers': '4 Layers (Anti-Microbial + UV)', 'Diameter': '1120 mm', 'Height': '1240 mm' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 2, discountPct: 5 }],
    rating: 4.8,
    reviewCount: 310,
    basePrice: 7800,
    mrp: 8900
  },
  {
    id: 'p_tap_1',
    name: 'Jaquar Continental Brass Bib Cock with Wall Flange',
    brand: 'Jaquar',
    category: 'Plumbing & Sanitary',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    description: 'Solid forged brass body bib tap with high-spec chrome plating and smooth ceramic disc cartridge for leak-free lifetime operation.',
    sku: 'TAP-JAQ-CNT-BIB',
    specifications: { 'Material': 'High Purity Virgin Brass', 'Finish': 'Chrome Plated 0.3 micron', 'Inlet Size': '1/2 inch BSP', 'Warranty': '10 Years Jaquar' },
    minOrderQty: 2,
    bulkDiscountTiers: [{ minQty: 10, discountPct: 8 }],
    rating: 4.9,
    reviewCount: 189,
    basePrice: 1150,
    mrp: 1390
  },
  {
    id: 'p_pump_1',
    name: 'Crompton 1.0 HP Self-Priming Monoblock Pump',
    brand: 'Crompton',
    category: 'Plumbing & Sanitary',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=800&q=80',
    description: 'Brass impeller motor pump engineered for rapid water lift from ground sump tanks to multi-story rooftop tanks.',
    sku: 'PMP-CRM-1HP-MB',
    specifications: { 'Power': '1.0 HP (0.75 kW)', 'Head Range': '6 to 45 meters', 'Flow Rate': '2800 LPH', 'Winding': '100% Pure Copper' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 3, discountPct: 6 }],
    rating: 4.7,
    reviewCount: 142,
    basePrice: 5800,
    mrp: 6800
  },
  {
    id: 'p_upvc_drain_1',
    name: 'Supreme SWR UPVC Drainage Pipe 110mm (4")',
    brand: 'Supreme',
    category: 'Plumbing & Sanitary',
    unit: 'Piece (3m)',
    imageUrl: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
    description: 'Rubber ring jointed soil and waste rainwater drainage pipe with ultraviolet degradation resistance.',
    sku: 'PIP-SUP-SWR-110',
    specifications: { 'Diameter': '110 mm (4 inch)', 'Joint Type': 'Ringfit / Pushfit socket', 'Length': '3 meters', 'Standard': 'IS 13592' },
    minOrderQty: 3,
    bulkDiscountTiers: [{ minQty: 15, discountPct: 6 }],
    rating: 4.7,
    reviewCount: 98,
    basePrice: 720,
    mrp: 850
  },
  {
    id: 'p_faucet_1',
    name: 'Kohler Health Faucet with 1.2m SS Flexible Hose',
    brand: 'Kohler',
    category: 'Plumbing & Sanitary',
    unit: 'Set',
    imageUrl: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=80',
    description: 'Ergonomic spray trigger hand hygiene faucet with kink-resistant stainless steel braided water supply hose.',
    sku: 'SNT-KOH-HLTH-FC',
    specifications: { 'Material': 'Engineered ABS + Chrome SS Hose', 'Hose Length': '1.2 meters', 'Working Pressure': '0.5 to 5.0 bar' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 5, discountPct: 8 }],
    rating: 4.8,
    reviewCount: 215,
    basePrice: 1490,
    mrp: 1800
  },
  {
    id: 'p_valve_1',
    name: 'Zoloto Forged Brass Ball Valve 1" Full Bore',
    brand: 'Zoloto',
    category: 'Plumbing & Sanitary',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=800&q=80',
    description: 'Heavy duty quarter-turn quarter-opening shutoff ball valve with PTFE sealing for zero dripping pipelines.',
    sku: 'VLV-ZOL-1IN-FB',
    specifications: { 'Body': 'Forged Brass Chrome Finish', 'Rating': 'PN 25 (350 PSI)', 'Bore': 'Full Bore 25mm' },
    minOrderQty: 2,
    bulkDiscountTiers: [{ minQty: 10, discountPct: 8 }],
    rating: 4.9,
    reviewCount: 76,
    basePrice: 650,
    mrp: 780
  },
  {
    id: 'p_sanitary_basin_1',
    name: 'Hindware Italian Wall-Hung Ceramic Wash Basin',
    brand: 'Hindware',
    category: 'Plumbing & Sanitary',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&w=800&q=80',
    description: 'Vitreous china glossy white washbasin with overflow hole and pre-punched single faucet hole.',
    sku: 'SAN-HND-BSN-WHT',
    specifications: { 'Material': 'Vitreous China Glossy', 'Size': '550 x 420 x 180 mm', 'Color': 'Alpine White' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 4, discountPct: 6 }],
    rating: 4.8,
    reviewCount: 168,
    basePrice: 2200,
    mrp: 2650
  },

  // 4. Paints, Primers & Waterproofing (8 items)
  {
    id: 'p_paint_1',
    name: 'Asian Paints Apex Ultima Weatherproof Emulsion',
    brand: 'Asian Paints',
    category: 'Paints & Waterproofing',
    unit: '20 Litre Drum',
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    description: 'Advanced anti-algal, dirt pick-up resistance exterior architectural emulsion with ColorStay UV technology providing 10-year exterior wall warranty.',
    sku: 'PNT-AP-APEX-20L',
    specifications: { 'Finish': 'Rich Sheen', 'Coverage': '55-65 sq ft/litre (2 coats)', 'Warranty': '10 Years Performance', 'Pack Size': '20 Litres' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 3, discountPct: 6 }, { minQty: 6, discountPct: 12 }],
    rating: 4.8,
    reviewCount: 388,
    basePrice: 5850,
    mrp: 6600
  },
  {
    id: 'p_paint_2',
    name: 'Berger Silk Glamor Luxury Interior Emulsion',
    brand: 'Berger Paints',
    category: 'Paints & Waterproofing',
    unit: '10 Litre Bucket',
    imageUrl: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=800&q=80',
    description: '100% acrylic interior paint with crystal reflective pigments that give living room and bedroom walls an ultra-smooth silk glow.',
    sku: 'PNT-BRG-SLK-10L',
    specifications: { 'Type': 'Luxury Interior Emulsion', 'Washability': 'High Scrub Resistant', 'Coverage': '140-160 sq ft/L (1 coat)' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 2, discountPct: 5 }],
    rating: 4.7,
    reviewCount: 165,
    basePrice: 3450,
    mrp: 3950
  },
  {
    id: 'p_waterproof_1',
    name: 'Dr. Fixit 101 LW+ Integral Liquid Waterproofing',
    brand: 'Dr. Fixit',
    category: 'Paints & Waterproofing',
    unit: '5 Litre Can',
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80',
    description: 'Integral liquid waterproofing compound mixed with cement mortar and concrete to prevent dampness and corrosion of rebars in foundations.',
    sku: 'WPF-DRF-101LW-5L',
    specifications: { 'Dosage': '200 ml per 50 kg cement bag', 'Form': 'Free-flowing dark brown liquid', 'Standards': 'IS 2645:2003' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 4, discountPct: 8 }, { minQty: 10, discountPct: 15 }],
    rating: 4.9,
    reviewCount: 410,
    basePrice: 840,
    mrp: 990
  },
  {
    id: 'p_putty_1',
    name: 'Birla White Wall Care Putty (Polymer Modified)',
    brand: 'Birla White',
    category: 'Paints & Waterproofing',
    unit: '40 kg Bag',
    imageUrl: 'https://images.unsplash.com/photo-1574359411659-15573a27fd0c?auto=format&fit=crop&w=800&q=80',
    description: 'White cement based putty with extra polymer bonding that seals pinholes on plaster surfaces creating a mirror-like paint base.',
    sku: 'PTY-BRL-40KG',
    specifications: { 'Base': 'White Portland Cement + Polymers', 'Pot Life': '2 Hours after mixing', 'Coverage': '16-20 sq ft/kg (2 coats)' },
    minOrderQty: 2,
    bulkDiscountTiers: [{ minQty: 10, discountPct: 5 }, { minQty: 25, discountPct: 10 }],
    rating: 4.8,
    reviewCount: 270,
    basePrice: 890,
    mrp: 1050
  },
  {
    id: 'p_enamel_1',
    name: 'Asian Paints Apcolite Premium Gloss Enamel (White)',
    brand: 'Asian Paints',
    category: 'Paints & Waterproofing',
    unit: '4 Litre Can',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    description: 'Tough mirror-gloss solvent-based enamel for metal gates, safety grills, wooden doors, and window frames.',
    sku: 'ENM-AP-APC-4L',
    specifications: { 'Type': 'Synthetic Solvent Enamel', 'Drying Time': '3-4 Hours surface dry', 'Finish': 'High Mirror Gloss' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 4, discountPct: 7 }],
    rating: 4.7,
    reviewCount: 130,
    basePrice: 1280,
    mrp: 1480
  },
  {
    id: 'p_primer_1',
    name: 'Dulux Promise Exterior Acrylic Primer',
    brand: 'Dulux',
    category: 'Paints & Waterproofing',
    unit: '10 Litre Bucket',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    description: 'Deep penetrating alkali-resistant water-based base primer designed to bind porous masonry prior to emulsion application.',
    sku: 'PRM-DLX-EXT-10L',
    specifications: { 'Base': 'Modified Acrylic Copolymer', 'Dilution': '1:1 with clean water', 'Coverage': '100-120 sq ft/L' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 3, discountPct: 6 }],
    rating: 4.6,
    reviewCount: 88,
    basePrice: 1650,
    mrp: 1920
  },
  {
    id: 'p_roller_1',
    name: 'Stanley Pro 9-Inch Microfiber Paint Roller Set',
    brand: 'Stanley',
    category: 'Paints & Waterproofing',
    unit: 'Set (Roller + Tray + 2 Sleeves)',
    imageUrl: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=800&q=80',
    description: 'Lint-free high absorption microfiber roller with heavy duty cage frame and deep ribbed paint loading tray.',
    sku: 'ACC-STN-RLR-9IN',
    specifications: { 'Roller Width': '9 inches (230mm)', 'Pile Height': '12 mm medium pile', 'Handle': 'Threaded for extension pole' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 5, discountPct: 8 }],
    rating: 4.8,
    reviewCount: 145,
    basePrice: 480,
    mrp: 600
  },
  {
    id: 'p_waterproof_roof_1',
    name: 'Dr. Fixit Newcoat Ezee Cool Roof Waterproof Coating',
    brand: 'Dr. Fixit',
    category: 'Paints & Waterproofing',
    unit: '10 Litre Bucket',
    imageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80',
    description: 'High build elastomeric heat reflecting waterproof coating for building terraces and exposed flat concrete roofs.',
    sku: 'WPF-DRF-NCT-10L',
    specifications: { 'Elongation': '> 300%', 'Solar Reflectance Index': 'SRI > 105 (Reduces rooftop temp by 5-7°C)', 'Pack': '10 Litres' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 3, discountPct: 7 }],
    rating: 4.8,
    reviewCount: 94,
    basePrice: 3200,
    mrp: 3750
  },

  // 5. Power Tools & Equipment (8 items)
  {
    id: 'p_tool_1',
    name: 'Bosch GBH 2-26 DRE Professional Rotary Hammer Drill',
    brand: 'Bosch',
    category: 'Power Tools & Hardware',
    unit: 'Unit + Kitbox',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=800&q=80',
    description: 'Heavy duty 800W rotary hammer with 2.7 Joules impact energy, SDS-plus toolholder, and 3 modes (drilling, hammer drilling, chiseling).',
    sku: 'TLS-BSH-GBH226',
    specifications: { 'Rated Power': '800 Watts', 'Impact Energy': '2.7 Joules', 'Drilling Dia in Concrete': '4-26 mm', 'Weight': '2.8 kg', 'Toolholder': 'SDS Plus' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 3, discountPct: 5 }, { minQty: 6, discountPct: 10 }],
    rating: 4.9,
    reviewCount: 620,
    basePrice: 8450,
    mrp: 9900
  },
  {
    id: 'p_tool_2',
    name: 'DeWalt DWE4010 4-Inch 750W Heavy Duty Angle Grinder',
    brand: 'DeWalt',
    category: 'Power Tools & Hardware',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=800&q=80',
    description: 'High-torque compact grinder with sealed ball bearings and epoxy coated windings for metal cutting, weld dressing, and concrete slicing.',
    sku: 'TLS-DEW-DWE4010',
    specifications: { 'Power': '750 Watts', 'No-load Speed': '11,000 RPM', 'Disc Diameter': '100 mm (4 inch)', 'Spindle': 'M10' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 3, discountPct: 6 }],
    rating: 4.8,
    reviewCount: 380,
    basePrice: 2850,
    mrp: 3400
  },
  {
    id: 'p_tool_3',
    name: 'Makita 4100NH 125mm Tile & Marble Cutter 1300W',
    brand: 'Makita',
    category: 'Power Tools & Hardware',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=800&q=80',
    description: 'High-speed professional stone cutter with adjustable depth gauge and water feed hose for wet granite slicing.',
    sku: 'TLS-MAK-4100NH',
    specifications: { 'Input Power': '1300 Watts', 'Blade Dia': '110-125 mm', 'Max Cutting Depth': '34 mm', 'Speed': '13,000 RPM' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 2, discountPct: 5 }],
    rating: 4.8,
    reviewCount: 210,
    basePrice: 4600,
    mrp: 5300
  },
  {
    id: 'p_tool_4',
    name: 'Stanley STDC4410 1400W Circular Woodworking Saw',
    brand: 'Stanley',
    category: 'Power Tools & Hardware',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=800&q=80',
    description: '7-inch carbide tipped circular blade saw with 45-degree bevel adjustment for rapid plywood framing and shuttering cuts.',
    sku: 'TLS-STN-CSAW-1400',
    specifications: { 'Power': '1400 Watts', 'Blade Size': '185 mm (7-1/4")', 'Depth of Cut at 90°': '62 mm' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 2, discountPct: 6 }],
    rating: 4.7,
    reviewCount: 154,
    basePrice: 4200,
    mrp: 4950
  },
  {
    id: 'p_tool_5',
    name: 'iBELL 200A Inverter IGBT Arc Welding Machine',
    brand: 'iBELL',
    category: 'Power Tools & Hardware',
    unit: 'Kit with Cables',
    imageUrl: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
    description: 'Portable anti-stick MMA welding inverter with digital amp display and built-in hot start for structural steel fabrication.',
    sku: 'TLS-IBL-WLD-200',
    specifications: { 'Current Output': '20 to 200 Amperes', 'Electrode Range': '1.6 mm to 4.0 mm', 'Duty Cycle': '60% at 200A', 'Technology': 'IGBT Inverter' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 2, discountPct: 5 }],
    rating: 4.6,
    reviewCount: 182,
    basePrice: 5900,
    mrp: 6990
  },
  {
    id: 'p_tool_6',
    name: 'Bosch Professional Cordless 18V Impact Driver GDR 180-LI',
    brand: 'Bosch',
    category: 'Power Tools & Hardware',
    unit: 'Set (with 2x 2.0Ah Batteries & Charger)',
    imageUrl: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=800&q=80',
    description: 'High torque 160 Nm cordless impact driver with 1/4" internal hex shank for roofing screws, anchors and timber framing.',
    sku: 'TLS-BSH-GDR180',
    specifications: { 'Torque': '160 Nm', 'Battery': '18V 2.0Ah Li-ion (2 included)', 'Impact Rate': '0-3600 bpm' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 2, discountPct: 6 }],
    rating: 4.9,
    reviewCount: 290,
    basePrice: 9800,
    mrp: 11500
  },
  {
    id: 'p_tool_7',
    name: 'Dongcheng 1500W Heavy Demolition Breaker',
    brand: 'Dongcheng',
    category: 'Power Tools & Hardware',
    unit: 'Unit with 2 Chisels',
    imageUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=800&q=80',
    description: 'Massive 16 kg heavy demolition jackhammer with 45 Joules single strike impact for breaking reinforced concrete slabs and rock.',
    sku: 'TLS-DNG-DMB-1500',
    specifications: { 'Power': '1500 Watts', 'Impact Rate': '1450 BPM', 'Blow Energy': '45 Joules', 'Hex Shank': '30 mm' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 2, discountPct: 8 }],
    rating: 4.8,
    reviewCount: 95,
    basePrice: 13500,
    mrp: 15900
  },
  {
    id: 'p_tool_8',
    name: 'Black+Decker 650W Variable Speed Jigsaw',
    brand: 'Black+Decker',
    category: 'Power Tools & Hardware',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?auto=format&fit=crop&w=800&q=80',
    description: 'Curved wood and metal jigsaw with bevel cutting mechanism and tool-less blade clamp.',
    sku: 'TLS-BND-JGS-650',
    specifications: { 'Power': '650 Watts', 'Stroke Length': '19 mm', 'Max Wood Depth': '85 mm' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 2, discountPct: 5 }],
    rating: 4.7,
    reviewCount: 112,
    basePrice: 2750,
    mrp: 3200
  },

  // 6. Hardware, Wood & Security (8 items)
  {
    id: 'p_wood_1',
    name: 'CenturyPly Club Prime 18mm BWP Marine Plywood',
    brand: 'CenturyPly',
    category: 'Wood, Tiles & Hardware',
    unit: 'Sheet (8x4 ft)',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    description: 'Boiling Waterproof IS 710 marine plywood infused with patented Firewall and ViroKill nano-technology against borers and termites.',
    sku: 'PLY-CEN-18MM-8X4',
    specifications: { 'Thickness': '18 mm', 'Sheet Size': '8 ft x 4 ft (32 sq ft)', 'Grade': 'IS 710 Marine BWP', 'Warranty': '30 Years Century Guarantee' },
    minOrderQty: 2,
    bulkDiscountTiers: [{ minQty: 10, discountPct: 6 }, { minQty: 25, discountPct: 12 }],
    rating: 4.9,
    reviewCount: 310,
    basePrice: 3850,
    mrp: 4400
  },
  {
    id: 'p_lock_1',
    name: 'Godrej Nav-Tal 7 Levers Hardened Brass Padlock',
    brand: 'Godrej',
    category: 'Wood, Tiles & Hardware',
    unit: 'Piece with 3 Keys',
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
    description: 'Iconic heavy brass padlock with hacksaw-resistant hardened steel shackle and precision 7-brass lever mechanism.',
    sku: 'LCK-GDJ-NVTL-7L',
    specifications: { 'Body Material': 'Solid Forged Brass', 'Shackle': 'Hardened Electroplated Steel', 'Levers': '7 Levers Anti-Pick' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 5, discountPct: 8 }],
    rating: 4.9,
    reviewCount: 480,
    basePrice: 620,
    mrp: 750
  },
  {
    id: 'p_lock_2',
    name: 'Yale Smart Biometric Digital Door Lock YDR 4110+',
    brand: 'Yale',
    category: 'Wood, Tiles & Hardware',
    unit: 'Set',
    imageUrl: 'https://images.unsplash.com/photo-1558002038-95d1055907df?auto=format&fit=crop&w=800&q=80',
    description: 'Touchscreen smart lock with one-touch fingerprint scan, PIN code access, mechanical override key, and anti-tamper security alarm.',
    sku: 'LCK-YAL-YDR4110',
    specifications: { 'Access Modes': 'Fingerprint (100 users), PIN Code, Key', 'Door Thickness': '35 mm - 80 mm', 'Emergency Power': '9V Battery Terminal' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 2, discountPct: 8 }],
    rating: 4.8,
    reviewCount: 140,
    basePrice: 18500,
    mrp: 22000
  },
  {
    id: 'p_hinge_1',
    name: 'Ebco Stainless Steel 304 Bearing Hinges (5" x 3" x 3mm)',
    brand: 'Ebco',
    category: 'Wood, Tiles & Hardware',
    unit: 'Pair (2 Pcs)',
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    description: 'Rust-proof SS 304 ball-bearing heavy door hinges supporting heavy teak wood main entrance doors smoothly.',
    sku: 'HNG-EBC-SS304-5IN',
    specifications: { 'Material': 'AISI 304 Stainless Steel', 'Size': '5 inch x 3 inch x 3 mm thickness', 'Load Capacity': '60 kg per pair' },
    minOrderQty: 2,
    bulkDiscountTiers: [{ minQty: 10, discountPct: 8 }],
    rating: 4.8,
    reviewCount: 110,
    basePrice: 420,
    mrp: 520
  },
  {
    id: 'p_screw_1',
    name: 'Hilti Zinc Plated Drywall & Wood Screws Box (3.5x25mm)',
    brand: 'Hilti',
    category: 'Wood, Tiles & Hardware',
    unit: 'Box of 1,000 Pcs',
    imageUrl: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=800&q=80',
    description: 'Bugle head Phillips drive self-tapping black phosphate screws for gypsum boards and timber battens.',
    sku: 'SCR-HLT-3.5X25',
    specifications: { 'Size': '3.5 mm x 25 mm', 'Quantity': '1,000 Screws per box', 'Coating': 'Black Phosphated Corrosion Shield' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 4, discountPct: 8 }],
    rating: 4.7,
    reviewCount: 95,
    basePrice: 380,
    mrp: 470
  },
  {
    id: 'p_handles_1',
    name: 'Dorma Brass Mortise Door Handle Set with Key Cylinder',
    brand: 'Dorma',
    category: 'Wood, Tiles & Hardware',
    unit: 'Set',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    description: 'Contemporary architectural antique brass finish lever handles with 60mm double cylinder mortise lock.',
    sku: 'HND-DRM-AB-60',
    specifications: { 'Finish': 'Antique Brass Satin', 'Material': 'Solid Brass Body', 'Locking': 'Computerized Brass Dimple Keys' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 4, discountPct: 7 }],
    rating: 4.8,
    reviewCount: 88,
    basePrice: 2890,
    mrp: 3450
  },
  {
    id: 'p_teak_1',
    name: 'Seasoned Burma Teak Wood Batten Rafter (3" x 2")',
    brand: 'GreenTimber',
    category: 'Wood, Tiles & Hardware',
    unit: 'Running Foot (10 ft length)',
    imageUrl: 'https://images.unsplash.com/photo-1544717302-de2939b7ef71?auto=format&fit=crop&w=800&q=80',
    description: 'Kiln dried 100% genuine knot-free seasoned teak timber for luxury door frames, windows, and customized furniture.',
    sku: 'WOD-TEK-3X2-10FT',
    specifications: { 'Dimension': '3 inch x 2 inch', 'Length': '10 feet', 'Moisture Content': '< 10%', 'Species': 'Tectona Grandis' },
    minOrderQty: 4,
    bulkDiscountTiers: [{ minQty: 20, discountPct: 8 }],
    rating: 4.9,
    reviewCount: 64,
    basePrice: 1950,
    mrp: 2300
  },
  {
    id: 'p_fevicol_1',
    name: 'Fevicol SH Synthetic Resin Adhesive (10 kg Bucket)',
    brand: 'Pidilite',
    category: 'Wood, Tiles & Hardware',
    unit: 'Bucket (10 kg)',
    imageUrl: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?auto=format&fit=crop&w=800&q=80',
    description: 'Unmatched bond strength wood glue for pasting laminates, veneer sheets, and carpentry woodwork.',
    sku: 'ADH-FEV-SH-10KG',
    specifications: { 'Base': 'Polyvinyl Acetate Emulsion', 'Viscosity': '250 to 350 Poise', 'Setting Time': '4 to 6 Hours' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 3, discountPct: 6 }],
    rating: 4.9,
    reviewCount: 380,
    basePrice: 2150,
    mrp: 2450
  },

  // 7. Safety Gear & Site Essentials (8 items)
  {
    id: 'p_safety_1',
    name: 'Karam ISI Ventilated Construction Safety Helmet',
    brand: 'Karam',
    category: 'Safety & Site Essentials',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    description: 'High impact HDPE site worker protective helmet with 6-point textile suspension and adjustable ratchet headband.',
    sku: 'SFT-KRM-HLMT-YEL',
    specifications: { 'Standard': 'IS 2925:1984', 'Material': 'Impact-Proof Polymer', 'Color': 'Safety Yellow / White' },
    minOrderQty: 2,
    bulkDiscountTiers: [{ minQty: 10, discountPct: 10 }, { minQty: 50, discountPct: 20 }],
    rating: 4.8,
    reviewCount: 220,
    basePrice: 240,
    mrp: 320
  },
  {
    id: 'p_safety_2',
    name: 'Allen Cooper Steel-Toe Leather Safety Work Boots',
    brand: 'Allen Cooper',
    category: 'Safety & Site Essentials',
    unit: 'Pair',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    description: 'Oil & acid resistant double density PU sole safety shoes with 200 Joules impact resistant steel toe cap.',
    sku: 'SFT-ALN-SHOE-10',
    specifications: { 'Upper': 'Genuine Grain Leather', 'Toe Cap': '200J Impact Steel', 'Sole': 'Dual Density PU Anti-Skid', 'Standard': 'IS 15298' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 5, discountPct: 8 }, { minQty: 20, discountPct: 15 }],
    rating: 4.7,
    reviewCount: 180,
    basePrice: 1850,
    mrp: 2400
  },
  {
    id: 'p_safety_3',
    name: '3M High Visibility Neon Reflective Safety Jacket',
    brand: '3M',
    category: 'Safety & Site Essentials',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    description: 'Lightweight breathable polyester mesh vest with 2-inch wide 3M Scotchlite retroreflective micro-prismatic bands.',
    sku: 'SFT-3M-VJCK-GRN',
    specifications: { 'Fabric': '120 GSM Fluorescent Polyester', 'Reflective Tape': '3M Scotchlite 500cd/lux', 'Closure': 'Heavy Duty Front Zipper' },
    minOrderQty: 5,
    bulkDiscountTiers: [{ minQty: 20, discountPct: 12 }, { minQty: 100, discountPct: 22 }],
    rating: 4.8,
    reviewCount: 310,
    basePrice: 180,
    mrp: 250
  },
  {
    id: 'p_safety_4',
    name: 'Udyogi Full Body Scaffold Fall Arrest Safety Harness',
    brand: 'Udyogi',
    category: 'Safety & Site Essentials',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    description: 'Industrial high-altitude working safety harness with forged dorsal D-ring and 2-meter energy absorbing lanyard hook.',
    sku: 'SFT-UDY-HRNS-DBL',
    specifications: { 'Webbing': '44mm High Tenacity Polyester', 'Breaking Strength': '25 kN', 'Lanyard': 'Energy Absorber with Scaffold Hook' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 5, discountPct: 10 }],
    rating: 4.9,
    reviewCount: 94,
    basePrice: 1650,
    mrp: 2100
  },
  {
    id: 'p_safety_5',
    name: '3M 9004V N95 Dust & Particulate Filtering Respirator',
    brand: '3M',
    category: 'Safety & Site Essentials',
    unit: 'Box of 10 Pcs',
    imageUrl: 'https://images.unsplash.com/photo-1584634731339-252c581abfc5?auto=format&fit=crop&w=800&q=80',
    description: 'Cool flow exhalation valve mask protecting masonry and grinding workers from fine silica dust and fumes.',
    sku: 'SFT-3M-9004V-10',
    specifications: { 'Filtration': '95% Fine Airborne Particulates', 'Valve': '3M Proprietary Cool Flow Valve', 'Pack': '10 Masks' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 5, discountPct: 10 }],
    rating: 4.8,
    reviewCount: 260,
    basePrice: 550,
    mrp: 700
  },
  {
    id: 'p_safety_6',
    name: 'Heavy Duty Leather Riggers Work Gloves (Pair)',
    brand: 'Karam',
    category: 'Safety & Site Essentials',
    unit: 'Pack of 3 Pairs',
    imageUrl: 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&w=800&q=80',
    description: 'Split cowhide reinforced palm gloves for handling raw steel rebars, sharp sheet metal, and rough masonry stone.',
    sku: 'SFT-KRM-GLV-LTH',
    specifications: { 'Material': 'Selected Split Cowhide Leather', 'Cuff': 'Rubberized Safety Cuff', 'Pack': '3 Pairs' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 5, discountPct: 10 }],
    rating: 4.6,
    reviewCount: 112,
    basePrice: 420,
    mrp: 540
  },
  {
    id: 'p_safety_7',
    name: 'Stanley Anti-Scratch UV Protective Safety Goggles',
    brand: 'Stanley',
    category: 'Safety & Site Essentials',
    unit: 'Piece',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=800&q=80',
    description: 'Panoramic polycarbonate wraparound eye shield with anti-fog coating for grinding and chipping operations.',
    sku: 'SFT-STN-GOG-CLR',
    specifications: { 'Lens': 'Optical Grade Polycarbonate', 'UV Protection': '99.9% UV400', 'Impact Rating': 'ANSI Z87.1 High Velocity' },
    minOrderQty: 2,
    bulkDiscountTiers: [{ minQty: 10, discountPct: 12 }],
    rating: 4.7,
    reviewCount: 145,
    basePrice: 190,
    mrp: 260
  },
  {
    id: 'p_safety_8',
    name: 'Ceasefire 4kg ABC Stored Pressure Fire Extinguisher',
    brand: 'Ceasefire',
    category: 'Safety & Site Essentials',
    unit: 'Unit with Wall Bracket',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    description: 'Multi-class MAP based fire extinguisher for electrical switchboards, site timber storage, and fuel safety.',
    sku: 'SFT-CSR-EXT-4KG',
    specifications: { 'Capacity': '4 kg MAP Powder', 'Fire Rating': '3A 21B', 'Discharge Time': '> 13 seconds' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 3, discountPct: 8 }],
    rating: 4.9,
    reviewCount: 88,
    basePrice: 2850,
    mrp: 3400
  },

  // 8. Tiles, Marbles & Flooring (8 items)
  {
    id: 'p_tile_1',
    name: 'Kajaria Grandeur Glazed Vitrified Tiles (600x1200mm)',
    brand: 'Kajaria',
    category: 'Wood, Tiles & Hardware',
    unit: 'Box (2 Pcs / 15.5 sq ft)',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    description: 'Mirror-finish Statuario Italian marble pattern glazed vitrified flooring tile with stain-resistant nano polish.',
    sku: 'TIL-KAJ-600X1200',
    specifications: { 'Dimensions': '600 x 1200 mm (2x4 ft)', 'Surface': 'High Gloss Polished', 'Coverage per Box': '15.5 sq ft (2 Tiles)' },
    minOrderQty: 5,
    bulkDiscountTiers: [{ minQty: 20, discountPct: 6 }, { minQty: 50, discountPct: 12 }],
    rating: 4.9,
    reviewCount: 215,
    basePrice: 1350,
    mrp: 1650
  },
  {
    id: 'p_tile_2',
    name: 'Somany Anti-Skid Rustic Bathroom Tiles (300x300mm)',
    brand: 'Somany',
    category: 'Wood, Tiles & Hardware',
    unit: 'Box (10 Pcs / 9.68 sq ft)',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    description: 'R11 slip rating textured porcelain ceramic tiles specially engineered for wet shower areas and balconies.',
    sku: 'TIL-SMN-300X300-SKD',
    specifications: { 'Dimensions': '300 x 300 mm (1x1 ft)', 'Surface': 'Matte Anti-Skid R11', 'Box Contents': '10 Tiles' },
    minOrderQty: 4,
    bulkDiscountTiers: [{ minQty: 15, discountPct: 6 }],
    rating: 4.7,
    reviewCount: 98,
    basePrice: 520,
    mrp: 640
  },
  {
    id: 'p_adhesive_1',
    name: 'Roff New Construction Tile Adhesive (T02)',
    brand: 'Roff (Pidilite)',
    category: 'Wood, Tiles & Hardware',
    unit: '20 kg Bag',
    imageUrl: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=800&q=80',
    description: 'Polymer modified cementitious dry powder adhesive for fixing ceramic, vitrified tiles and natural stone onto floors.',
    sku: 'ADH-ROF-T02-20KG',
    specifications: { 'Type': 'C1TE Standard Adhesive', 'Bed Thickness': '3 to 6 mm', 'Coverage': '55-60 sq ft per 20kg bag' },
    minOrderQty: 2,
    bulkDiscountTiers: [{ minQty: 10, discountPct: 6 }, { minQty: 25, discountPct: 12 }],
    rating: 4.8,
    reviewCount: 175,
    basePrice: 460,
    mrp: 550
  },
  {
    id: 'p_granite_1',
    name: 'Black Galaxy Premium Indian Granite Slab',
    brand: 'StoneCraft',
    category: 'Wood, Tiles & Hardware',
    unit: 'Sq Ft (approx 18mm thickness)',
    imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    description: 'Dense crystalline natural granite with golden copper flakes for luxury kitchen countertops, stairs, and vanity tops.',
    sku: 'STN-BLK-GLX-SQFT',
    specifications: { 'Thickness': '18 mm to 20 mm', 'Finish': 'Mirror Polish Gangsaw Cut', 'Origin': 'Ongole, Andhra Pradesh' },
    minOrderQty: 50,
    bulkDiscountTiers: [{ minQty: 150, discountPct: 8 }],
    rating: 4.9,
    reviewCount: 82,
    basePrice: 195,
    mrp: 240
  },
  {
    id: 'p_grout_1',
    name: 'Laticrete Spectralock Pro Epoxy Tile Grout (5 kg)',
    brand: 'Laticrete',
    category: 'Wood, Tiles & Hardware',
    unit: 'Kit (5 kg)',
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80',
    description: 'Chemical resistant waterproof 3-component epoxy grout that never discolors, cracks, or fosters mold.',
    sku: 'GRT-LAT-EPX-5KG',
    specifications: { 'Type': '100% Solid Epoxy 3-Part Grout', 'Joint Width': '1.5 mm to 12 mm', 'Colors': 'Ivory, Silver Shadow, Charcoal' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 4, discountPct: 8 }],
    rating: 4.9,
    reviewCount: 130,
    basePrice: 1250,
    mrp: 1480
  },
  {
    id: 'p_spacer_1',
    name: 'Tile Levelling Clips & Reusable Wedges Kit (2mm)',
    brand: 'ProLevel',
    category: 'Wood, Tiles & Hardware',
    unit: 'Set (300 Clips + 100 Wedges + Pliers)',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    description: 'Precision tile alignment system eliminating lippage and uneven joints during vitrified tile flooring laying.',
    sku: 'TLS-LVL-KIT-2MM',
    specifications: { 'Joint Spacer': '2.0 mm thickness', 'Tile Thickness Range': '3 mm to 12 mm', 'Included': 'Leveling Pliers included' },
    minOrderQty: 1,
    bulkDiscountTiers: [{ minQty: 3, discountPct: 8 }],
    rating: 4.7,
    reviewCount: 96,
    basePrice: 850,
    mrp: 1050
  },
  {
    id: 'p_step_1',
    name: 'Granite Step & Riser Bullnosed Tile Set (4ft x 1ft)',
    brand: 'StoneCraft',
    category: 'Wood, Tiles & Hardware',
    unit: 'Set (1 Tread + 1 Riser)',
    imageUrl: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=800&q=80',
    description: 'Pre-cut full bullnosed granite staircase steps with groove lines for anti-slip grip and rapid staircase cladding.',
    sku: 'STN-STP-BLN-4FT',
    specifications: { 'Step Size': '4 ft x 1 ft (1200 x 300 mm)', 'Riser Size': '4 ft x 6 inch (1200 x 150 mm)', 'Profile': 'Full Round Bullnose' },
    minOrderQty: 5,
    bulkDiscountTiers: [{ minQty: 20, discountPct: 8 }],
    rating: 4.8,
    reviewCount: 45,
    basePrice: 920,
    mrp: 1100
  },
  {
    id: 'p_cobble_1',
    name: 'Interlocking Concrete Paver Blocks (80mm Heavy Duty)',
    brand: 'UltraPaver',
    category: 'Wood, Tiles & Hardware',
    unit: 'Sq Ft (approx 3.5 Pcs)',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80',
    description: 'Zig-zag high compressive strength M40 grade concrete pavers for parking lots, driveways, and industrial yards.',
    sku: 'PVR-ZZ-80MM-M40',
    specifications: { 'Grade': 'M40 High Strength', 'Thickness': '80 mm', 'Pattern': 'Interlocking Zig-Zag' },
    minOrderQty: 100,
    bulkDiscountTiers: [{ minQty: 500, discountPct: 10 }],
    rating: 4.8,
    reviewCount: 65,
    basePrice: 48,
    mrp: 58
  }
];

// Verified retail hardware & building supplies stores
const retailersData = [
  {
    id: 'ret_1',
    name: 'Balaji Hardware & Building Materials',
    address: 'Plot 42, 100 Feet Ring Road, JP Nagar 6th Phase, Bengaluru, Karnataka 560078',
    distance: 1.2,
    rating: 4.8,
    reviewsCount: 342,
    isServiceable: true,
    deliveryTypes: ['express', 'scheduled', 'bulk'],
    phone: '+91 98450 12345',
    isOpen: true,
    operatingHours: '07:30 AM - 09:00 PM',
    deliveryRadiusKm: 12,
    gstin: '29ABCDE1234F1Z5',
    bannerImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    avatarImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    badges: ['Verified Partner', 'Fast Dispatch', 'Bulk Stockist'],
    totalProductsCount: 1450
  },
  {
    id: 'ret_2',
    name: 'Sri Krishna Steel & Cement Corporation',
    address: 'Shop 18, Commercial Street, Jayanagar 4th Block, Bengaluru, Karnataka 560011',
    distance: 2.8,
    rating: 4.7,
    reviewsCount: 289,
    isServiceable: true,
    deliveryTypes: ['scheduled', 'bulk'],
    phone: '+91 98450 67890',
    isOpen: true,
    operatingHours: '08:00 AM - 08:30 PM',
    deliveryRadiusKm: 15,
    gstin: '29BCDEF2345G2Z6',
    bannerImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80',
    avatarImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    badges: ['Tata Tiscon Authorized', 'UltraTech Direct Dealer'],
    totalProductsCount: 820
  },
  {
    id: 'ret_3',
    name: 'Metro Electricals & Lighting Hub',
    address: '22/B, Outer Ring Road, BTM Layout 2nd Stage, Bengaluru, Karnataka 560076',
    distance: 3.5,
    rating: 4.9,
    reviewsCount: 512,
    isServiceable: true,
    deliveryTypes: ['express', 'scheduled'],
    phone: '+91 98450 34567',
    isOpen: true,
    operatingHours: '09:00 AM - 09:30 PM',
    deliveryRadiusKm: 10,
    gstin: '29CDEFG3456H3Z7',
    bannerImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80',
    avatarImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    badges: ['Havells Gold Club', 'Schneider Certified', 'Express 45-Min'],
    totalProductsCount: 2300
  },
  {
    id: 'ret_4',
    name: 'Prime Sanitaryware & Astral Plumbing Superstore',
    address: '104, Bannerghatta Main Road, Arekere, Bengaluru, Karnataka 560076',
    distance: 4.1,
    rating: 4.6,
    reviewsCount: 198,
    isServiceable: true,
    deliveryTypes: ['express', 'scheduled', 'bulk'],
    phone: '+91 98450 78901',
    isOpen: true,
    operatingHours: '08:30 AM - 08:30 PM',
    deliveryRadiusKm: 14,
    gstin: '29DEFGHI4567I4Z8',
    bannerImage: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=1200&q=80',
    avatarImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    badges: ['Astral Master Stockist', 'Jaquar Experience Hub'],
    totalProductsCount: 1650
  },
  {
    id: 'ret_5',
    name: 'Apex Paints, Woodcraft & Power Tools',
    address: '56, Hosur Main Road, Kudlu Gate, Electronic City Phase 1, Bengaluru, Karnataka 560068',
    distance: 5.7,
    rating: 4.8,
    reviewsCount: 420,
    isServiceable: true,
    deliveryTypes: ['express', 'scheduled', 'bulk'],
    phone: '+91 98450 89012',
    isOpen: true,
    operatingHours: '08:00 AM - 09:00 PM',
    deliveryRadiusKm: 18,
    gstin: '29EFGHIJ5678J5Z9',
    bannerImage: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1200&q=80',
    avatarImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    badges: ['Bosch Authorized Service', 'Asian Paints Colour Idea', 'CenturyPly Partner'],
    totalProductsCount: 3100
  },
  {
    id: 'ret_6',
    name: 'Kajaria Grand & Safety Gear Mart',
    address: '88, Sarjapur Main Road, Bellandur, Bengaluru, Karnataka 560103',
    distance: 6.9,
    rating: 4.7,
    reviewsCount: 165,
    isServiceable: true,
    deliveryTypes: ['scheduled', 'bulk'],
    phone: '+91 98450 90123',
    isOpen: true,
    operatingHours: '09:00 AM - 08:00 PM',
    deliveryRadiusKm: 15,
    gstin: '29FGHIJK6789K6Z0',
    bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    avatarImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    badges: ['Kajaria Exclusive Gallery', '3M Safety Partner'],
    totalProductsCount: 980
  }
];

// Categories definition
const categoriesData = [
  {
    id: 'cat_structural',
    name: 'Structural & Masonry',
    slug: 'structural-masonry',
    subcategories: 'Cement, TMT Steel Rebars, Red Clay Bricks, River Sand, AAC Blocks',
    icon: '🏗️',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    itemCount: 85
  },
  {
    id: 'cat_electrical',
    name: 'Electrical & Lighting',
    slug: 'electrical-lighting',
    subcategories: 'Copper Wires, Modular Switches, MCB Breakers, LED Floodlights, Conduits',
    icon: '⚡',
    image: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?auto=format&fit=crop&w=800&q=80',
    itemCount: 140
  },
  {
    id: 'cat_plumbing',
    name: 'Plumbing & Sanitary',
    slug: 'plumbing-sanitary',
    subcategories: 'CPVC & UPVC Pipes, Water Tanks, Brass Faucets, Pumps, Valves',
    icon: '🚰',
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80',
    itemCount: 95
  },
  {
    id: 'cat_paints',
    name: 'Paints & Waterproofing',
    slug: 'paints-waterproofing',
    subcategories: 'Apex Weatherproof Emulsions, Primers, Dr. Fixit Waterproofing, Wall Putty',
    icon: '🎨',
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=800&q=80',
    itemCount: 110
  },
  {
    id: 'cat_powertools',
    name: 'Power Tools & Hardware',
    slug: 'power-tools-hardware',
    subcategories: 'Hammer Drills, Angle Grinders, Marble Cutters, Welding Machines, Saws',
    icon: '🔧',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=800&q=80',
    itemCount: 120
  },
  {
    id: 'cat_woodtiles',
    name: 'Wood, Tiles & Hardware',
    slug: 'wood-tiles-hardware',
    subcategories: 'BWP Marine Plywood, Mortise Locks, Vitrified Tiles, Adhesives, Hinges',
    icon: '🪵',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    itemCount: 160
  },
  {
    id: 'cat_safety',
    name: 'Safety & Site Essentials',
    slug: 'safety-site-essentials',
    subcategories: 'Safety Helmets, High-Vis Vests, Steel Toe Boots, Safety Harnesses, N95 Masks',
    icon: '🦺',
    image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    itemCount: 75
  }
];

// Generate offers for each product across retailers
const offers = [];
productData.forEach((p) => {
  retailersData.forEach((ret, rIdx) => {
    const priceVariance = (rIdx % 3 === 0 ? 0 : (rIdx % 2 === 0 ? -0.03 : 0.04));
    const price = Math.round(p.basePrice * (1 + priceVariance));
    const stock = 15 + ((p.id.length * 17 + rIdx * 29) % 85);
    const mins = 30 + Math.round(ret.distance * 8);

    offers.push({
      id: `off_${p.id}_${ret.id}`,
      productId: p.id,
      retailerId: ret.id,
      price: price,
      mrp: p.mrp,
      stock: stock,
      isAvailable: true,
      estimatedDeliveryMins: mins,
      storeName: ret.name,
      storeDistance: ret.distance,
      storeRating: ret.rating
    });
  });
});

// App promotional banners
const promotionalBanners = [
  {
    id: 'ban_1',
    title: 'Monsoon Proofing Bonanza',
    subtitle: 'Flat 15% OFF on Dr. Fixit, Berger & Asian Paints Exterior Sealer',
    code: 'WATERPROOF15',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    badge: 'Limited Monsoon Deal'
  },
  {
    id: 'ban_2',
    title: 'Direct From Rolling Mills',
    subtitle: 'Tata Tiscon 550D & JSW Neosteel Rebars at Guaranteed Wholesale Rates',
    code: 'BULKSTEEL',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80',
    badge: 'Same-Day Site Crane Delivery'
  },
  {
    id: 'ban_3',
    title: 'Pro Power Tools Clearance',
    subtitle: 'Up to 25% OFF on Bosch, DeWalt, Makita Rotary Hammers & Grinders',
    code: 'PROTOOL25',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=1200&q=80',
    badge: 'Official Brand Warranty'
  }
];

// Delivery drivers
const driversData = [
  {
    id: 'drv_1',
    name: 'Ramesh Gowda',
    phone: '+91 98451 11223',
    vehicleType: 'Tata Ace (1.5 Ton)',
    vehicleNumber: 'KA-05-AB-4567',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    rating: 4.9,
    tripsCompleted: 1420
  },
  {
    id: 'drv_2',
    name: 'Suresh Kumar',
    phone: '+91 98452 22334',
    vehicleType: 'Mahindra Bolero Maxi Truck (2.5 Ton)',
    vehicleNumber: 'KA-01-CD-8901',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    rating: 4.8,
    tripsCompleted: 980
  },
  {
    id: 'drv_3',
    name: 'Manjunath B.',
    phone: '+91 98453 33445',
    vehicleType: 'Eicher Pro 6-Wheeler Tipper (8 Ton)',
    vehicleNumber: 'KA-51-EF-2345',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    rating: 4.95,
    tripsCompleted: 2150
  }
];

// Build final catalog object
const catalog = {
  metadata: {
    datasetVersion: '3.3.0',
    totalCategories: categoriesData.length,
    totalRetailers: retailersData.length,
    totalProducts: productData.length,
    totalOffers: offers.length,
    totalDrivers: driversData.length,
    totalBanners: promotionalBanners.length,
    lastUpdated: new Date().toISOString()
  },
  categories: categoriesData,
  retailers: retailersData,
  products: productData.map(p => {
    const { basePrice, mrp, ...rest } = p;
    return rest;
  }),
  offers: offers,
  promotionalBanners: promotionalBanners,
  drivers: driversData
};

// Write catalog.json
const catalogPath = path.resolve('public/data/catalog.json');
fs.writeFileSync(catalogPath, JSON.stringify(catalog, null, 2), 'utf8');

// Generate and write src/services/mockData.ts as well
const tsContent = `// Auto-generated BuildIt Static Catalog & Mock Data
// Generated from scripts/generateCatalog.mjs

import type { CategoryItem, Product, Retailer, RetailerProductOffer, Order, Promotion, DeliveryTrip, DriverStats, DeliveryAddress } from '../types';

export const mockCategories: CategoryItem[] = ${JSON.stringify(catalog.categories, null, 2)};

export const mockRetailers: Retailer[] = ${JSON.stringify(catalog.retailers, null, 2)};

export const mockProducts: Product[] = ${JSON.stringify(catalog.products, null, 2)};

export const mockOffers: RetailerProductOffer[] = ${JSON.stringify(catalog.offers, null, 2)};

export const mockAddresses: DeliveryAddress[] = [
  {
    id: 'addr_1',
    label: 'Site',
    name: 'Sellu (Chief Site Engineer)',
    phone: '+91 98450 11223',
    line1: 'Tower B, 4th Floor Slab Casting Site',
    line2: 'Prestige Lakeside, Varthur Kodi',
    city: 'Bengaluru',
    pincode: '560087',
    isDefault: true,
    coordinates: { lat: 12.957, lng: 77.744 }
  },
  {
    id: 'addr_2',
    label: 'Office',
    name: 'Sellu (Procurement Dept)',
    phone: '+91 98450 11223',
    line1: 'Level 4, BuildIt Construction HQ',
    line2: '100 Feet Road, Indiranagar',
    city: 'Bengaluru',
    pincode: '560038',
    coordinates: { lat: 12.978, lng: 77.641 }
  },
  {
    id: 'addr_3',
    label: 'Home',
    name: 'Sellu',
    phone: '+91 98450 11223',
    line1: 'Villa 18, Palm Meadows',
    line2: 'Airport Whitefield Road',
    city: 'Bengaluru',
    pincode: '560066',
    coordinates: { lat: 12.969, lng: 77.75 }
  }
];

export const mockPromotions: Promotion[] = [
  {
    id: 'promo_1',
    title: 'Monsoon Proofing 15% OFF',
    productName: 'Dr. Fixit & Waterproofing Chemicals',
    discountPct: 15,
    couponCode: 'WATERPROOF15',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    status: 'active',
    minOrderValue: 2500,
    maxDiscount: 1000
  },
  {
    id: 'promo_2',
    title: 'Tata Tiscon Bulk Contractor Rebate',
    productName: 'Tata Tiscon 550D TMT Rebars',
    discountPct: 8,
    couponCode: 'BULKSTEEL',
    startDate: '2026-09-01',
    endDate: '2026-10-15',
    status: 'active',
    minOrderValue: 25000,
    maxDiscount: 5000
  },
  {
    id: 'promo_3',
    title: 'Bosch Power Tools Weekend Bonanza',
    productName: 'Rotary Hammers & Angle Grinders',
    discountPct: 12,
    couponCode: 'BOSCH12',
    startDate: '2026-09-05',
    endDate: '2026-09-12',
    status: 'active',
    minOrderValue: 5000,
    maxDiscount: 1500
  }
];

export const mockOrders: Order[] = [
  {
    id: 'ord_1001',
    customerId: 'cust_01',
    customerName: 'Sellu (Chief Contractor)',
    customerPhone: '+91 98450 11223',
    retailerId: 'ret_1',
    retailerName: 'Balaji Hardware & Building Materials',
    status: 'out_for_delivery',
    items: [
      {
        id: 'cart_1',
        product: mockProducts[0],
        offer: mockOffers[0],
        retailer: mockRetailers[0],
        quantity: 50
      },
      {
        id: 'cart_2',
        product: mockProducts[2],
        offer: mockOffers[12],
        retailer: mockRetailers[0],
        quantity: 20
      }
    ],
    subtotal: 34850,
    gst: 6273,
    deliveryFee: 450,
    discountAmount: 1500,
    couponCode: 'BUILDIT1500',
    totalAmount: 40073,
    deliveryAddress: mockAddresses[0],
    deliveryType: 'bulk',
    deliveryModel: 'third_party_logistics',
    estimatedDeliveryMins: 38,
    paymentMethod: 'UPI',
    paymentStatus: 'paid',
    driverId: 'drv_1',
    driverName: 'Ramesh Gowda',
    driverPhone: '+91 98451 11223',
    driverVehicle: 'Tata Ace (KA-05-AB-4567)',
    otp: '4829',
    createdAt: new Date(Date.now() - 42 * 60 * 1000).toISOString()
  },
  {
    id: 'ord_1002',
    customerId: 'cust_01',
    customerName: 'Sellu (Chief Contractor)',
    customerPhone: '+91 98450 11223',
    retailerId: 'ret_3',
    retailerName: 'Metro Electricals & Lighting Hub',
    status: 'delivered',
    items: [
      {
        id: 'cart_3',
        product: mockProducts[8],
        offer: mockOffers[48],
        retailer: mockRetailers[2],
        quantity: 6
      }
    ],
    subtotal: 14700,
    gst: 2646,
    deliveryFee: 150,
    discountAmount: 0,
    totalAmount: 17496,
    deliveryAddress: mockAddresses[1],
    deliveryType: 'express',
    deliveryModel: 'retailer_fleet',
    paymentMethod: 'Card',
    paymentStatus: 'paid',
    driverId: 'drv_2',
    driverName: 'Suresh Kumar',
    driverPhone: '+91 98452 22334',
    driverVehicle: 'Mahindra Bolero (KA-01-CD-8901)',
    otp: '9183',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString()
  }
];

export const initialMockOrders = mockOrders;

export const mockDeliveryTrips: DeliveryTrip[] = [
  {
    id: 'trip_101',
    orderId: 'ord_1001',
    pickupStore: 'Balaji Hardware & Building Materials',
    pickupAddress: 'Plot 42, 100 Feet Ring Road, JP Nagar 6th Phase, Bengaluru',
    dropAddress: 'Tower B, Prestige Lakeside, Whitefield Road, Bengaluru - 560087',
    distanceKm: 8.4,
    earnings: 450,
    status: 'ongoing',
    payloadWeight: '2,500 kg (Cement + TMT)',
    itemSummary: '50x UltraTech Cement, 20x Tata Tiscon 12mm Rebars',
    customerPhone: '+91 98450 11223',
    otp: '4829'
  },
  {
    id: 'trip_102',
    orderId: 'ord_1002',
    pickupStore: 'Metro Electricals & Lighting Hub',
    pickupAddress: '22/B, Outer Ring Road, BTM Layout 2nd Stage',
    dropAddress: 'Site 14, HSR Layout Sector 2, Bengaluru - 560102',
    distanceKm: 3.2,
    earnings: 280,
    status: 'available',
    payloadWeight: '45 kg (Cables & Switches)',
    itemSummary: '10x Havells Wire 2.5sq mm, 5x Schneider Modular Switch Box',
    customerPhone: '+91 98450 44556',
    otp: '9183'
  }
];

export const mockDriverTrips = mockDeliveryTrips;

export const mockDriverStats: DriverStats = {
  todayEarnings: 2450,
  weeklyEarnings: 16800,
  completedTrips: 7,
  onlineHours: 6.5,
  rating: 4.9,
  acceptanceRate: 98
};
`;

const mockDataPath = path.resolve('src/services/mockData.ts');
fs.writeFileSync(mockDataPath, tsContent, 'utf8');
console.log('Saved catalog.json and mockData.ts with all exports successfully!');
